/* eslint-disable no-console */
const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding dev database...');

  const destructive = process.env.DESTRUCTIVE_SEED === 'true';
  if (destructive) {
    console.log('Destructive seed enabled: clearing existing data');
    await prisma.prompt.deleteMany();
    await prisma.unit.deleteMany();
    await prisma.lang.deleteMany();
  }

  // Languages with prompts: native script -> romanization (not translation)
  const langs = [
    {
      name: 'Japanese',
      units: [
        {
          name: 'Greetings',
          prompts: [
            { content: 'こんにちは', answer: 'konnichiwa' },
            { content: 'ありがとう', answer: 'arigatou' },
            { content: 'すみません', answer: 'sumimasen' },
            { content: 'ごめんなさい', answer: 'gomennasai' },
            { content: 'お願いします', answer: 'onegaishimasu' },
            { content: 'おはよう', answer: 'ohayou' },
            { content: 'こんばんは', answer: 'konbanwa' },
            { content: 'さようなら', answer: 'sayounara' },
            { content: 'はい', answer: 'hai' },
            { content: 'いいえ', answer: 'iie' },
          ],
        },
        {
          name: 'Numbers 1-10',
          prompts: [
            { content: '一', answer: 'ichi' },
            { content: '二', answer: 'ni' },
            { content: '三', answer: 'san' },
            { content: '四', answer: 'yon' },
            { content: '五', answer: 'go' },
            { content: '六', answer: 'roku' },
            { content: '七', answer: 'nana' },
            { content: '八', answer: 'hachi' },
            { content: '九', answer: 'kyuu' },
            { content: '十', answer: 'juu' },
          ],
        },
        {
          name: 'Food & Drink',
          prompts: [
            { content: '水', answer: 'mizu' },
            { content: 'お茶', answer: 'ocha' },
            { content: 'コーヒー', answer: 'koohii' },
            { content: 'ご飯', answer: 'gohan' },
            { content: '麺', answer: 'men' },
            { content: 'パン', answer: 'pan' },
            { content: '牛乳', answer: 'gyuunyuu' },
            { content: 'ジュース', answer: 'juusu' },
            { content: 'ビール', answer: 'biiru' },
            { content: 'ワイン', answer: 'wain' },
            { content: 'りんご', answer: 'ringo' },
            { content: '肉', answer: 'niku' },
          ],
        },
        {
          name: 'Common Verbs',
          prompts: [
            { content: '行く', answer: 'iku' },
            { content: '来る', answer: 'kuru' },
            { content: '食べる', answer: 'taberu' },
            { content: '飲む', answer: 'nomu' },
            { content: '見る', answer: 'miru' },
            { content: '話す', answer: 'hanasu' },
            { content: '書く', answer: 'kaku' },
            { content: '読む', answer: 'yomu' },
            { content: 'する', answer: 'suru' },
            { content: 'ある', answer: 'aru' },
            { content: 'いる', answer: 'iru' },
            { content: '走る', answer: 'hashiru' },
          ],
        },
        {
          name: 'Family',
          prompts: [
            { content: '母', answer: 'haha' },
            { content: '父', answer: 'chichi' },
            { content: '兄', answer: 'ani' },
            { content: '姉', answer: 'ane' },
            { content: '弟', answer: 'otouto' },
            { content: '妹', answer: 'imouto' },
            { content: '息子', answer: 'musuko' },
            { content: '娘', answer: 'musume' },
            { content: '家族', answer: 'kazoku' },
            { content: '友達', answer: 'tomodachi' },
            { content: '夫', answer: 'otto' },
            { content: '妻', answer: 'tsuma' },
          ],
        },
        {
          name: 'Days & Time',
          prompts: [
            { content: '月曜日', answer: 'getsuyoubi' },
            { content: '火曜日', answer: 'kayoubi' },
            { content: '水曜日', answer: 'suiyoubi' },
            { content: '木曜日', answer: 'mokuyoubi' },
            { content: '金曜日', answer: 'kinyoubi' },
            { content: '土曜日', answer: 'doyoubi' },
            { content: '日曜日', answer: 'nichiyoubi' },
            { content: '今日', answer: 'kyou' },
            { content: '明日', answer: 'ashita' },
            { content: '昨日', answer: 'kinou' },
          ],
        },
        {
          name: 'Places',
          prompts: [
            { content: '学校', answer: 'gakkou' },
            { content: '家', answer: 'ie' },
            { content: '店', answer: 'mise' },
            { content: '病院', answer: 'byouin' },
            { content: '駅', answer: 'eki' },
            { content: '公園', answer: 'kouen' },
            { content: '会社', answer: 'kaisha' },
            { content: '銀行', answer: 'ginkou' },
            { content: '図書館', answer: 'toshokan' },
            { content: '空港', answer: 'kuukou' },
            { content: '市場', answer: 'ichiba' },
            { content: 'レストラン', answer: 'resutoran' },
          ],
        },
      ],
    },
    {
      name: 'Korean',
      units: [
        {
          name: 'Greetings',
          prompts: [
            { content: '안녕하세요', answer: 'annyeonghaseyo' },
            { content: '안녕히 계세요', answer: 'annyeonghi gyeseyo' },
            { content: '안녕히 가세요', answer: 'annyeonghi gaseyo' },
            { content: '감사합니다', answer: 'gamsahamnida' },
            { content: '죄송합니다', answer: 'joesonghamnida' },
            { content: '제발', answer: 'jebal' },
            { content: '네', answer: 'ne' },
            { content: '아니요', answer: 'aniyo' },
            { content: '안녕', answer: 'annyeong' },
            { content: '잘 부탁합니다', answer: 'jal butakhamnida' },
          ],
        },
        {
          name: 'Numbers 1-10 (Sino)',
          prompts: [
            { content: '일', answer: 'il' },
            { content: '이', answer: 'i' },
            { content: '삼', answer: 'sam' },
            { content: '사', answer: 'sa' },
            { content: '오', answer: 'o' },
            { content: '육', answer: 'yuk' },
            { content: '칠', answer: 'chil' },
            { content: '팔', answer: 'pal' },
            { content: '구', answer: 'gu' },
            { content: '십', answer: 'sip' },
          ],
        },
        {
          name: 'Food & Drink',
          prompts: [
            { content: '물', answer: 'mul' },
            { content: '차', answer: 'cha' },
            { content: '커피', answer: 'keopi' },
            { content: '밥', answer: 'bap' },
            { content: '면', answer: 'myeon' },
            { content: '빵', answer: 'ppang' },
            { content: '우유', answer: 'uyu' },
            { content: '주스', answer: 'juseu' },
            { content: '맥주', answer: 'maekju' },
            { content: '와인', answer: 'wain' },
            { content: '사과', answer: 'sagwa' },
            { content: '고기', answer: 'gogi' },
          ],
        },
        {
          name: 'Common Verbs',
          prompts: [
            { content: '가다', answer: 'gada' },
            { content: '오다', answer: 'oda' },
            { content: '먹다', answer: 'meokda' },
            { content: '마시다', answer: 'masida' },
            { content: '보다', answer: 'boda' },
            { content: '읽다', answer: 'ikda' },
            { content: '쓰다', answer: 'sseuda' },
            { content: '하다', answer: 'hada' },
            { content: '있다', answer: 'itda' },
            { content: '없다', answer: 'eopda' },
            { content: '걷다', answer: 'geotda' },
            { content: '달리다', answer: 'dallida' },
          ],
        },
        {
          name: 'Family',
          prompts: [
            { content: '어머니', answer: 'eomeoni' },
            { content: '아버지', answer: 'abeoji' },
            { content: '형', answer: 'hyeong' },
            { content: '누나', answer: 'nuna' },
            { content: '오빠', answer: 'oppa' },
            { content: '언니', answer: 'eonni' },
            { content: '동생', answer: 'dongsaeng' },
            { content: '아들', answer: 'adeul' },
            { content: '딸', answer: 'ttal' },
            { content: '가족', answer: 'gajok' },
            { content: '친구', answer: 'chingu' },
            { content: '남편', answer: 'nampyeon' },
          ],
        },
        {
          name: 'Days & Time',
          prompts: [
            { content: '월요일', answer: 'woryoil' },
            { content: '화요일', answer: 'hwayoil' },
            { content: '수요일', answer: 'suyoil' },
            { content: '목요일', answer: 'mogyoil' },
            { content: '금요일', answer: 'geumyoil' },
            { content: '토요일', answer: 'toyoil' },
            { content: '일요일', answer: 'iryoil' },
            { content: '오늘', answer: 'oneul' },
            { content: '내일', answer: 'naeil' },
            { content: '어제', answer: 'eoje' },
          ],
        },
        {
          name: 'Places',
          prompts: [
            { content: '학교', answer: 'hakgyo' },
            { content: '집', answer: 'jib' },
            { content: '가게', answer: 'gage' },
            { content: '병원', answer: 'byeongwon' },
            { content: '역', answer: 'yeok' },
            { content: '공원', answer: 'gongwon' },
            { content: '회사', answer: 'hoesa' },
            { content: '은행', answer: 'eunhaeng' },
            { content: '도서관', answer: 'doseogwan' },
            { content: '공항', answer: 'gonghang' },
            { content: '시장', answer: 'sijang' },
            { content: '레스토랑', answer: 'reseutorang' },
          ],
        },
      ],
    },
    {
      name: 'Chinese',
      units: [
        {
          name: 'Greetings',
          prompts: [
            { content: '你好', answer: 'ni hao' },
            { content: '谢谢', answer: 'xie xie' },
            { content: '请', answer: 'qing' },
            { content: '对不起', answer: 'dui bu qi' },
            { content: '再见', answer: 'zai jian' },
            { content: '早上好', answer: 'zao shang hao' },
            { content: '晚上好', answer: 'wan shang hao' },
            { content: '没关系', answer: 'mei guan xi' },
            { content: '好的', answer: 'hao de' },
            { content: '不客气', answer: 'bu ke qi' },
          ],
        },
        {
          name: 'Numbers 1-10',
          prompts: [
            { content: '一', answer: 'yi' },
            { content: '二', answer: 'er' },
            { content: '三', answer: 'san' },
            { content: '四', answer: 'si' },
            { content: '五', answer: 'wu' },
            { content: '六', answer: 'liu' },
            { content: '七', answer: 'qi' },
            { content: '八', answer: 'ba' },
            { content: '九', answer: 'jiu' },
            { content: '十', answer: 'shi' },
          ],
        },
        {
          name: 'Food & Drink',
          prompts: [
            { content: '水', answer: 'shui' },
            { content: '茶', answer: 'cha' },
            { content: '咖啡', answer: 'ka fei' },
            { content: '米饭', answer: 'mi fan' },
            { content: '面条', answer: 'mian tiao' },
            { content: '面包', answer: 'mian bao' },
            { content: '牛奶', answer: 'niu nai' },
            { content: '果汁', answer: 'guo zhi' },
            { content: '啤酒', answer: 'pi jiu' },
            { content: '葡萄酒', answer: 'pu tao jiu' },
            { content: '苹果', answer: 'ping guo' },
            { content: '肉', answer: 'rou' },
          ],
        },
        {
          name: 'Common Verbs',
          prompts: [
            { content: '去', answer: 'qu' },
            { content: '来', answer: 'lai' },
            { content: '吃', answer: 'chi' },
            { content: '喝', answer: 'he' },
            { content: '看', answer: 'kan' },
            { content: '读', answer: 'du' },
            { content: '写', answer: 'xie' },
            { content: '做', answer: 'zuo' },
            { content: '有', answer: 'you' },
            { content: '没有', answer: 'mei you' },
            { content: '走', answer: 'zou' },
            { content: '跑', answer: 'pao' },
          ],
        },
        {
          name: 'Family',
          prompts: [
            { content: '妈妈', answer: 'ma ma' },
            { content: '爸爸', answer: 'ba ba' },
            { content: '哥哥', answer: 'ge ge' },
            { content: '姐姐', answer: 'jie jie' },
            { content: '弟弟', answer: 'di di' },
            { content: '妹妹', answer: 'mei mei' },
            { content: '儿子', answer: 'er zi' },
            { content: '女儿', answer: 'nv er' },
            { content: '家人', answer: 'jia ren' },
            { content: '朋友', answer: 'peng you' },
            { content: '丈夫', answer: 'zhang fu' },
            { content: '妻子', answer: 'qi zi' },
          ],
        },
        {
          name: 'Days & Time',
          prompts: [
            { content: '星期一', answer: 'xing qi yi' },
            { content: '星期二', answer: 'xing qi er' },
            { content: '星期三', answer: 'xing qi san' },
            { content: '星期四', answer: 'xing qi si' },
            { content: '星期五', answer: 'xing qi wu' },
            { content: '星期六', answer: 'xing qi liu' },
            { content: '星期天', answer: 'xing qi tian' },
            { content: '今天', answer: 'jin tian' },
            { content: '明天', answer: 'ming tian' },
            { content: '昨天', answer: 'zuo tian' },
          ],
        },
        {
          name: 'Places',
          prompts: [
            { content: '学校', answer: 'xue xiao' },
            { content: '家', answer: 'jia' },
            { content: '商店', answer: 'shang dian' },
            { content: '医院', answer: 'yi yuan' },
            { content: '车站', answer: 'che zhan' },
            { content: '公园', answer: 'gong yuan' },
            { content: '公司', answer: 'gong si' },
            { content: '银行', answer: 'yin hang' },
            { content: '图书馆', answer: 'tu shu guan' },
            { content: '机场', answer: 'ji chang' },
            { content: '市场', answer: 'shi chang' },
            { content: '餐厅', answer: 'can ting' },
          ],
        },
        {
          name: 'Work & Business',
          prompts: [
            { content: '公司计划明年在上海开设新分部', answer: 'gong si ji hua ming nian zai shang hai kai she xin fen bu' },
            { content: '经理要求我们按时完成报告', answer: 'jing li yao qiu wo men an shi wan cheng bao gao' },
            { content: '他在会议上提出了一个重要建议', answer: 'ta zai hui yi shang ti chu le yi ge zhong yao jian yi' },
            { content: '这家企业正在寻找有经验的员工', answer: 'zhe jia qi ye zheng zai xun zhao you jing yan de yuan gong' },
            { content: '我们需要与外国客户保持良好关系', answer: 'wo men xu yao yu wai guo ke hu bao chi liang hao guan xi' },
            { content: '为了增加销量公司推出了新产品', answer: 'wei le zeng jia xiao liang gong si tui chu le xin chan pin' },
            { content: '她负责监督整个项目的进度', answer: 'ta fu ze jian du zheng ge xiang mu de jin du' },
            { content: '我对这份工作的待遇很满意', answer: 'wo dui zhe fen gong zuo de dai yu hen man yi' },
            { content: '尽管加班很多他仍然保持积极态度', answer: 'jin guan jia ban hen duo ta reng ran bao chi ji ji tai du' },
            { content: '合同的细节必须在今天下午确定', answer: 'he tong de xi jie bi xu zai jin tian xia wu que ding' },
            { content: '他们正在讨论公司的发展战略', answer: 'ta men zheng zai tao lun gong si de fa zhan zhan lue' },
            { content: '客户对我们提供的服务表示赞赏', answer: 'ke hu dui wo men ti gong de fu wu biao shi zan shang' },
            { content: '我想了解一下这个岗位的具体要求', answer: 'wo xiang liao jie yi xia zhe ge gang wei de ju ti yao qiu' },
            { content: '如果价格合适我们可以签署协议', answer: 'ru guo jia ge he shi wo men ke yi qian shu xie yi' },
            { content: '这次培训有助于提高员工的能力', answer: 'zhe ci pei xun you zhu yu ti gao yuan gong de neng li' },
            { content: '她在竞争中表现出色赢得了职位', answer: 'ta zai jing zheng zhong biao xian chu se ying de le zhi wei' },
            { content: '我们需要节省成本以保持利润', answer: 'wo men xu yao jie sheng cheng ben yi bao chi li run' },
            { content: '他负责联系供应商并安排运输', answer: 'ta fu ze lian xi gong ying shang bing an pai yun shu' },
            { content: '虽然工作压力大但他从不抱怨', answer: 'sui ran gong zuo ya li da dan ta cong bu bao yuan' },
            { content: '公司的成功离不开团队的合作', answer: 'gong si de cheng gong li bu kai tuan dui de he zuo' },
          ],
        },
        {
          name: 'Travel & Transportation',
          prompts: [
            { content: '我们计划下个月去云南旅游', answer: 'wo men ji hua xia ge yue qu yun nan lv you' },
            { content: '出发前别忘了检查护照和签证', answer: 'chu fa qian bie wang le jian cha hu zhao he qian zheng' },
            { content: '由于天气不好航班被取消了', answer: 'you yu tian qi bu hao hang ban bei qu xiao le' },
            { content: '她在网上预订了酒店和机票', answer: 'ta zai wang shang yu ding le jiu dian he ji piao' },
            { content: '导游向大家介绍当地的历史', answer: 'dao you xiang da jia jie shao dang di de li shi' },
            { content: '乘坐高铁可以节省很多时间', answer: 'cheng zuo gao tie ke yi jie sheng hen duo shi jian' },
            { content: '我在地图上寻找最近的地铁站', answer: 'wo zai di tu shang xun zhao zui jin de di tie zhan' },
            { content: '如果迷路了可以向路人求助', answer: 'ru guo mi lu le ke yi xiang lu ren qiu zhu' },
            { content: '旅行时要注意保管好自己的行李', answer: 'lv xing shi yao zhu yi bao guan hao zi ji de xing li' },
            { content: '他们决定沿着海边骑自行车', answer: 'ta men jue ding yan zhe hai bian qi zi xing che' },
            { content: '这个城市的公共交通非常方便', answer: 'zhe ge cheng shi de gong gong jiao tong fei chang fang bian' },
            { content: '我们在机场等了两个小时才登机', answer: 'wo men zai ji chang deng le liang ge xiao shi cai deng ji' },
            { content: '虽然路很远但风景非常美丽', answer: 'sui ran lu hen yuan dan feng jing fei chang mei li' },
            { content: '他通过旅行社安排了整个行程', answer: 'ta tong guo lv xing she an pai le zheng ge xing cheng' },
            { content: '为了避免堵车我们提前出发', answer: 'wei le bi mian du che wo men ti qian chu fa' },
            { content: '她喜欢在旅途中记录所见所闻', answer: 'ta xi huan zai lv tu zhong ji lu suo jian suo wen' },
            { content: '这家旅馆的服务让人感到舒适', answer: 'zhe jia lv guan de fu wu rang ren gan dao shu shi' },
            { content: '如果有时间我们去参观博物馆', answer: 'ru guo you shi jian wo men qu can guan bo wu guan' },
            { content: '他们在山顶拍了很多照片作为纪念', answer: 'ta men zai shan ding pai le hen duo zhao pian zuo wei ji nian' },
            { content: '每次旅行我都会尝试当地的特色菜', answer: 'mei ci lv xing wo dou hui chang shi dang di de te se cai' },
          ],
        },
        {
          name: 'Education & Learning',
          prompts: [
            { content: '学校鼓励学生参加课外活动', answer: 'xue xiao gu li xue sheng can jia ke wai huo dong' },
            { content: '她每天花两个小时复习功课', answer: 'ta mei tian hua liang ge xiao shi fu xi gong ke' },
            { content: '老师要求我们提前完成作业', answer: 'lao shi yao qiu wo men ti qian wan cheng zuo ye' },
            { content: '我对历史课非常感兴趣', answer: 'wo dui li shi ke fei chang gan xing qu' },
            { content: '尽管考试很难他还是取得了好成绩', answer: 'jin guan kao shi hen nan ta hai shi qu de le hao cheng ji' },
            { content: '我们在图书馆一起做研究', answer: 'wo men zai tu shu guan yi qi zuo yan jiu' },
            { content: '课堂讨论帮助我理解新的概念', answer: 'ke tang tao lun bang zhu wo li jie xin de gai nian' },
            { content: '学生必须遵守学校的规章制度', answer: 'xue sheng bi xu zun shou xue xiao de gui zhang zhi du' },
            { content: '他计划明年去国外留学', answer: 'ta ji hua ming nian qu guo wai liu xue' },
            { content: '为了提高口语她参加了语言角', answer: 'wei le ti gao kou yu ta can jia le yu yan jiao' },
            { content: '我需要查资料来写这篇论文', answer: 'wo xu yao cha zi liao lai xie zhe pian lun wen' },
            { content: '教授鼓励我们提出自己的观点', answer: 'jiao shou gu li wo men ti chu zi ji de guan dian' },
            { content: '他们正在准备大学入学考试', answer: 'ta men zheng zai zhun bei da xue ru xue kao shi' },
            { content: '如果有问题可以随时向老师请教', answer: 'ru guo you wen ti ke yi sui shi xiang lao shi qing jiao' },
            { content: '学校提供了丰富的学习资源', answer: 'xue xiao ti gong le feng fu de xue xi zi yuan' },
            { content: '他通过网络课程学习编程', answer: 'ta tong guo wang luo ke cheng xue xi bian cheng' },
            { content: '虽然课程很紧但她坚持每天阅读', answer: 'sui ran ke cheng hen jin dan ta jian chi mei tian yue du' },
            { content: '图书馆每周都会举办讲座', answer: 'tu shu guan mei zhou dou hui ju ban jiang zuo' },
            { content: '我对这个实验的结果非常好奇', answer: 'wo dui zhe ge shi yan de jie guo fei chang hao qi' },
            { content: '在学习过程中保持耐心非常重要', answer: 'zai xue xi guo cheng zhong bao chi nai xin fei chang zhong yao' },
          ],
        },
        {
          name: 'Culture & Society',
          prompts: [
            { content: '节日期间街道上充满了欢笑和音乐', answer: 'jie ri qi jian jie dao shang chong man le huan xiao he yin yue' },
            { content: '在中国春节是最重要的传统节日', answer: 'zai zhong guo chun jie shi zui zhong yao de chuan tong jie ri' },
            { content: '博物馆展示了很多古代文物', answer: 'bo wu guan zhan shi le hen duo gu dai wen wu' },
            { content: '他们正在讨论社会公平的问题', answer: 'ta men zheng zai tao lun she hui gong ping de wen ti' },
            { content: '这部电影反映了现代家庭的变化', answer: 'zhe bu dian ying fan ying le xian dai jia ting de bian hua' },
            { content: '老人喜欢在公园里下棋聊天', answer: 'lao ren xi huan zai gong yuan li xia qi liao tian' },
            { content: '他对不同文化之间的差异很感兴趣', answer: 'ta dui bu tong wen hua zhi jian de cha yi hen gan xing qu' },
            { content: '城市的发展带来了新的社会挑战', answer: 'cheng shi de fa zhan dai lai le xin de she hui tiao zhan' },
            { content: '我们应该尊重各地的风俗习惯', answer: 'wo men ying gai zun zhong ge di de feng su xi guan' },
            { content: '报纸报道了当地社区的活动', answer: 'bao zhi bao dao le dang di she qu de huo dong' },
            { content: '她喜欢阅读关于中国历史的书', answer: 'ta xi huan yue du guan yu zhong guo li shi de shu' },
            { content: '这个展览吸引了来自世界各地的游客', answer: 'zhe ge zhan lan xi yin le lai zi shi jie ge di de you ke' },
            { content: '他们通过音乐表达对生活的热爱', answer: 'ta men tong guo yin yue biao da dui sheng huo de re ai' },
            { content: '在公共场合要注意礼貌和行为', answer: 'zai gong gong chang he yao zhu yi li mao he xing wei' },
            { content: '传统艺术在年轻人中越来越受欢迎', answer: 'chuan tong yi shu zai nian qing ren zhong yue lai yue shou huan ying' },
            { content: '政府正在努力改善居民的生活条件', answer: 'zheng fu zheng zai nu li gai shan ju min de sheng huo tiao jian' },
            { content: '虽然观点不同他们仍然保持友好', answer: 'sui ran guan dian bu tong ta men reng ran bao chi you hao' },
            { content: '这个故事反映了社会的现实问题', answer: 'zhe ge gu shi fan ying le she hui de xian shi wen ti' },
            { content: '我参加了一个介绍中国茶文化的活动', answer: 'wo can jia le yi ge jie shao zhong guo cha wen hua de huo dong' },
            { content: '对环境的保护已经成为社会共识', answer: 'dui huan jing de bao hu yi jing cheng wei she hui gong shi' },
          ],
        },
        {
          name: 'Health & Lifestyle',
          prompts: [
            { content: '他每天早上坚持跑步半小时', answer: 'ta mei tian zao shang jian chi pao bu ban xiao shi' },
            { content: '医生建议我们多吃水果和蔬菜', answer: 'yi sheng jian yi wo men duo chi shui guo he shu cai' },
            { content: '虽然工作忙她仍然保持规律作息', answer: 'sui ran gong zuo mang ta reng ran bao chi gui lv zuo xi' },
            { content: '为了减肥他控制自己的饮食', answer: 'wei le jian fei ta kong zhi zi ji de yin shi' },
            { content: '充足的睡眠对健康非常重要', answer: 'chong zu de shui mian dui jian kang fei chang zhong yao' },
            { content: '她喜欢通过瑜伽来放松身心', answer: 'ta xi huan tong guo yu jia lai fang song shen xin' },
            { content: '如果感到压力大可以找朋友聊聊', answer: 'ru guo gan dao ya li da ke yi zhao peng you liao liao' },
            { content: '夏天出门要记得涂防晒霜', answer: 'xia tian chu men yao ji de tu fang shai shuang' },
            { content: '他因为感冒而缺席了会议', answer: 'ta yin wei gan mao er que xi le hui yi' },
            { content: '我们应该养成每天喝水的习惯', answer: 'wo men ying gai yang cheng mei tian he shui de xi guan' },
            { content: '医院里有很多人排队看病', answer: 'yi yuan li you hen duo ren pai dui kan bing' },
            { content: '他决定戒烟以改善身体状况', answer: 'ta jue ding jie yan yi gai shan shen ti zhuang kuang' },
            { content: '定期体检可以发现潜在问题', answer: 'ding qi ti jian ke yi fa xian qian zai wen ti' },
            { content: '她每天都会记录自己的饮食和运动', answer: 'ta mei tian dou hui ji lu zi ji de yin shi he yun dong' },
            { content: '尽管天气寒冷他们仍然去游泳', answer: 'jin guan tian qi han leng ta men reng ran qu you yong' },
            { content: '放假时她喜欢与家人一起登山', answer: 'fang jia shi ta xi huan yu jia ren yi qi deng shan' },
            { content: '如果感到疲倦就应该及时休息', answer: 'ru guo gan dao pi juan jiu ying gai ji shi xiu xi' },
            { content: '健康的生活方式需要长期坚持', answer: 'jian kang de sheng huo fang shi xu yao chang qi jian chi' },
            { content: '这个应用程序可以帮助你计算卡路里', answer: 'zhe ge ying yong cheng xu ke yi bang zhu ni ji suan ka lu li' },
            { content: '我们要注意保持心情愉快', answer: 'wo men yao zhu yi bao chi xin qing yu kuai' },
          ],
        },
        {
          name: 'Technology & Communication',
          prompts: [
            { content: '现代社会离不开互联网和智能手机', answer: 'xian dai she hui li bu kai hu lian wang he zhi neng shou ji' },
            { content: '她在网上发布了一篇关于教育的文章', answer: 'ta zai wang shang fa bu le yi pian guan yu jiao yu de wen zhang' },
            { content: '通过视频会议我们节省了很多时间', answer: 'tong guo shi pin hui yi wo men jie sheng le hen duo shi jian' },
            { content: '他喜欢用社交媒体分享旅行照片', answer: 'ta xi huan yong she jiao mei ti fen xiang lv xing zhao pian' },
            { content: '如果密码太简单账户容易被盗', answer: 'ru guo mi ma tai jian dan zhang hu rong yi bei dao' },
            { content: '这款软件可以帮助你管理日程', answer: 'zhe kuan ruan jian ke yi bang zhu ni guan li ri cheng' },
            { content: '我们需要升级电脑系统以提高效率', answer: 'wo men xu yao sheng ji dian nao xi tong yi ti gao xiao lv' },
            { content: '他习惯睡前阅读电子书', answer: 'ta xi guan shui qian yue du dian zi shu' },
            { content: '这个应用允许用户在线支付水电费', answer: 'zhe ge ying yong yun xu yong hu zai xian zhi fu shui dian fei' },
            { content: '公司正在开发一项新的通讯技术', answer: 'gong si zheng zai kai fa yi xiang xin de tong xun ji shu' },
            { content: '由于网络故障我们无法访问网站', answer: 'you yu wang luo gu zhang wo men wu fa fang wen wang zhan' },
            { content: '请确保数据备份以防丢失', answer: 'qing que bao shu ju bei fen yi fang diu shi' },
            { content: '她通过邮件确认了会议时间', answer: 'ta tong guo you jian que ren le hui yi shi jian' },
            { content: '在论坛上提问可以得到很多建议', answer: 'zai lun tan shang ti wen ke yi de dao hen duo jian yi' },
            { content: '我喜欢在博客里记录学习心得', answer: 'wo xi huan zai bo ke li ji lu xue xi xin de' },
            { content: '如果信号不好通话会中断', answer: 'ru guo xin hao bu hao tong hua hui zhong duan' },
            { content: '他们正在测试新的语音识别系统', answer: 'ta men zheng zai ce shi xin de yu yin shi bie xi tong' },
            { content: '这个网站提供免费的云存储空间', answer: 'zhe ge wang zhan ti gong mian fei de yun cun chu kong jian' },
            { content: '她在社交平台上发布了求助信息', answer: 'ta zai she jiao ping tai shang fa bu le qiu zhu xin xi' },
            { content: '使用公共电脑时要注意保护隐私', answer: 'shi yong gong gong dian nao shi yao zhu yi bao hu yin si' },
          ],
        },
        {
          name: 'Environment & Nature',
          prompts: [
            { content: '政府推出新政策鼓励回收利用', answer: 'zheng fu tui chu xin zheng ce gu li hui shou li yong' },
            { content: '我们应该减少使用塑料袋', answer: 'wo men ying gai jian shao shi yong su liao dai' },
            { content: '这个公园以美丽的自然风景闻名', answer: 'zhe ge gong yuan yi mei li de zi ran feng jing wen ming' },
            { content: '他每周参加社区的植树活动', answer: 'ta mei zhou can jia she qu de zhi shu huo dong' },
            { content: '为了保护海洋请不要随意扔垃圾', answer: 'wei le bao hu hai yang qing bu yao sui yi reng la ji' },
            { content: '最近的空气质量明显好转', answer: 'zui jin de kong qi zhi liang ming xian hao zhuan' },
            { content: '这条河里生活着很多珍贵的鱼类', answer: 'zhe tiao he li sheng huo zhe hen duo zhen gui de yu lei' },
            { content: '农民使用有机肥料提高土壤质量', answer: 'nong min shi yong you ji fei liao ti gao tu rang zhi liang' },
            { content: '他们呼吁人们节约用水', answer: 'ta men hu yu ren men jie yue yong shui' },
            { content: '长时间的干旱影响了当地农业', answer: 'chang shi jian de gan han ying xiang le dang di nong ye' },
            { content: '这座城市正在推广绿色交通', answer: 'zhe zuo cheng shi zheng zai tui guang lv se jiao tong' },
            { content: '森林火灾引起了社会广泛关注', answer: 'sen lin huo zai yin qi le she hui guang fan guan zhu' },
            { content: '我们在山上搭帐篷过夜', answer: 'wo men zai shan shang da zhang peng guo ye' },
            { content: '她喜欢在周末去郊外徒步', answer: 'ta xi huan zai zhou mo qu jiao wai tu bu' },
            { content: '保护动物是每个人的责任', answer: 'bao hu dong wu shi mei ge ren de ze ren' },
            { content: '这个地区的冬天经常下大雪', answer: 'zhe ge di qu de dong tian jing chang xia da xue' },
            { content: '为了减少污染他们改用电动车', answer: 'wei le jian shao wu ran ta men gai yong dian dong che' },
            { content: '雨林里的生态系统非常复杂', answer: 'yu lin li de sheng tai xi tong fei chang fu za' },
            { content: '他在文章中强调可持续发展', answer: 'ta zai wen zhang zhong qiang diao ke chi xu fa zhan' },
            { content: '我们计划周末去湖边野餐', answer: 'wo men ji hua zhou mo qu hu bian ye can' },
          ],
        },
        {
          name: 'Sports & Recreation',
          prompts: [
            { content: '他每周三和朋友一起打篮球', answer: 'ta mei zhou san he peng you yi qi da lan qiu' },
            { content: '这家健身房二十四小时开放', answer: 'zhe jia jian shen fang er shi si xiao shi kai fang' },
            { content: '参加马拉松需要长时间训练', answer: 'can jia ma la song xu yao chang shi jian xun lian' },
            { content: '她通过游泳保持身体健康', answer: 'ta tong guo you yong bao chi shen ti jian kang' },
            { content: '夏天我们经常在公园骑自行车', answer: 'xia tian wo men jing chang zai gong yuan qi zi xing che' },
            { content: '团队运动可以培养合作精神', answer: 'tuan dui yun dong ke yi pei yang he zuo jing shen' },
            { content: '他喜欢在家里练习太极拳', answer: 'ta xi huan zai jia li lian xi tai ji quan' },
            { content: '比赛开始前请做充分的热身', answer: 'bi sai kai shi qian qing zuo chong fen de re shen' },
            { content: '这个俱乐部提供各种户外活动', answer: 'zhe ge ju le bu ti gong ge zhong hu wai huo dong' },
            { content: '去年她在比赛中获得了冠军', answer: 'qu nian ta zai bi sai zhong huo de le guan jun' },
            { content: '如果天气好我们周末去爬山', answer: 'ru guo tian qi hao wo men zhou mo qu pa shan' },
            { content: '他打算学习一项新的体育项目', answer: 'ta da suan xue xi yi xiang xin de ti yu xiang mu' },
            { content: '观众在场边为选手加油', answer: 'guan zhong zai chang bian wei xuan shou jia you' },
            { content: '比分仍然保持零比零', answer: 'bi fen reng ran bao chi ling bi ling' },
            { content: '她对滑雪产生了浓厚兴趣', answer: 'ta dui hua xue chan sheng le nong hou xing qu' },
            { content: '我们在比赛后讨论了战术', answer: 'wo men zai bi sai hou tao lun le zhan shu' },
            { content: '这片场地需要提前预约', answer: 'zhe pian chang di xu yao ti qian yu yue' },
            { content: '他因受伤无法继续比赛', answer: 'ta yin shou shang wu fa ji xu bi sai' },
            { content: '每天下午操场上都有人跑步', answer: 'mei tian xia wu cao chang shang dou you ren pao bu' },
            { content: '保持良好的心态有助于提高成绩', answer: 'bao chi liang hao de xin tai you zhu yu ti gao cheng ji' },
          ],
        },
        {
          name: 'Shopping & Consumption',
          prompts: [
            { content: '她在商场挑选了一件合适的礼物', answer: 'ta zai shang chang tiao xuan le yi jian he shi de li wu' },
            { content: '打折季人们排队等待开门', answer: 'da zhe ji ren men pai dui deng dai kai men' },
            { content: '网购虽然方便但需要注意质量', answer: 'wang gou sui ran fang bian dan xu yao zhu yi zhi liang' },
            { content: '这家超市每天都有新鲜水果', answer: 'zhe jia chao shi mei tian dou you xin xian shui guo' },
            { content: '我用信用卡支付了全部费用', answer: 'wo yong xin yong ka zhi fu le quan bu fei yong' },
            { content: '如果商品有问题可以要求退换', answer: 'ru guo shang pin you wen ti ke yi yao qiu tui huan' },
            { content: '她喜欢在二手市场寻找便宜书籍', answer: 'ta xi huan zai er shou shi chang xun zhao pian yi shu ji' },
            { content: '这件衣服的质量比价格更重要', answer: 'zhe jian yi fu de zhi liang bi jia ge geng zhong yao' },
            { content: '购物前最好列出需要的物品', answer: 'gou wu qian zui hao lie chu xu yao de wu pin' },
            { content: '他在网上查阅商品的用户评价', answer: 'ta zai wang shang cha yue shang pin de yong hu ping jia' },
            { content: '这个商店提供免费送货服务', answer: 'zhe ge shang dian ti gong mian fei song huo fu wu' },
            { content: '他们决定分摊这次聚餐的费用', answer: 'ta men jue ding fen tan zhe ci ju can de fei yong' },
            { content: '我在市场上讨价还价买了便宜的菜', answer: 'wo zai shi chang shang tao jia huan jia mai le pian yi de cai' },
            { content: '她喜欢收集各种折扣券', answer: 'ta xi huan shou ji ge zhong zhe kou quan' },
            { content: '使用会员卡可以获得额外积分', answer: 'shi yong hui yuan ka ke yi huo de e wai ji fen' },
            { content: '这家店的售后服务很专业', answer: 'zhe jia dian de shou hou fu wu hen zhuan ye' },
            { content: '他为家人买了新家具', answer: 'ta wei jia ren mai le xin jia ju' },
            { content: '每月底我都会检查消费记录', answer: 'mei yue di wo dou hui jian cha xiao fei ji lu' },
            { content: '如果超出预算就需要调整计划', answer: 'ru guo chao chu yu suan jiu xu yao tiao zheng ji hua' },
            { content: '他们在夜市品尝了各种小吃', answer: 'ta men zai ye shi pin chang le ge zhong xiao chi' },
          ],
        },
        {
          name: 'Entertainment & Media',
          prompts: [
            { content: '这部电视剧在年轻人中非常流行', answer: 'zhe bu dian shi ju zai nian qing ren zhong fei chang liu xing' },
            { content: '我们一起去电影院看了新上映的电影', answer: 'wo men yi qi qu dian ying yuan kan le xin shang ying de dian ying' },
            { content: '她每天听广播了解最新消息', answer: 'ta mei tian ting guang bo liao jie zui xin xiao xi' },
            { content: '这位歌手的演唱会门票很快售罄', answer: 'zhe wei ge shou de yan chang hui men piao hen kuai shou qing' },
            { content: '他在音乐节上认识了很多朋友', answer: 'ta zai yin yue jie shang ren shi le hen duo peng you' },
            { content: '看纪录片可以扩大我们的视野', answer: 'kan ji lu pian ke yi kuo da wo men de shi ye' },
            { content: '她正在学习如何制作短视频', answer: 'ta zheng zai xue xi ru he zhi zuo duan shi pin' },
            { content: '这家博物馆周末对公众免费开放', answer: 'zhe jia bo wu guan zhou mo dui gong zhong mian fei kai fang' },
            { content: '通过阅读小说我放松了心情', answer: 'tong guo yue du xiao shuo wo fang song le xin qing' },
            { content: '他们组织了一场社区戏剧表演', answer: 'ta men zu zhi le yi chang she qu xi ju biao yan' },
            { content: '如果想提高口语可以参加话剧社', answer: 'ru guo xiang ti gao kou yu ke yi can jia hua ju she' },
            { content: '他在博客上评论了最新的电影', answer: 'ta zai bo ke shang ping lun le zui xin de dian ying' },
            { content: '电视节目讨论了教育改革的问题', answer: 'dian shi jie mu tao lun le jiao yu gai ge de wen ti' },
            { content: '这款游戏适合全家人一起玩', answer: 'zhe kuan you xi shi he quan jia ren yi qi wan' },
            { content: '她喜欢在闲暇时弹钢琴', answer: 'ta xi huan zai xian xia shi tan gang qin' },
            { content: '我们在音乐会上听到了经典作品', answer: 'wo men zai yin yue hui shang ting dao le jing dian zuo pin' },
            { content: '这家出版社计划推出一系列新书', answer: 'zhe jia chu ban she ji hua tui chu yi xi lie xin shu' },
            { content: '看演出前最好提前预订座位', answer: 'kan yan chu qian zui hao ti qian yu ding zuo wei' },
            { content: '这档综艺节目以幽默著称', answer: 'zhe dang zong yi jie mu yi you mo zhu cheng' },
            { content: '他正在准备拍摄一部短片', answer: 'ta zheng zai zhun bei pai she yi bu duan pian' },
          ],
        },
      ],
    },
    {
      name: 'Russian',
      units: [
        {
          name: 'Greetings',
          prompts: [
            { content: 'Привет', answer: 'privet' },
            { content: 'Здравствуйте', answer: 'zdravstvuyte' },
            { content: 'Спасибо', answer: 'spasibo' },
            { content: 'Пожалуйста', answer: 'pozhaluysta' },
            { content: 'До свидания', answer: 'do svidaniya' },
            { content: 'Извините', answer: 'izvinite' },
            { content: 'Хорошо', answer: 'khorosho' },
            { content: 'Плохо', answer: 'plokho' },
            { content: 'Да', answer: 'da' },
            { content: 'Нет', answer: 'net' },
          ],
        },
        {
          name: 'Numbers 1-10',
          prompts: [
            { content: 'один', answer: 'odin' },
            { content: 'два', answer: 'dva' },
            { content: 'три', answer: 'tri' },
            { content: 'четыре', answer: 'chetyre' },
            { content: 'пять', answer: 'pyat' },
            { content: 'шесть', answer: 'shest' },
            { content: 'семь', answer: 'sem' },
            { content: 'восемь', answer: 'vosem' },
            { content: 'девять', answer: 'devyat' },
            { content: 'десять', answer: 'desyat' },
          ],
        },
        {
          name: 'Food & Drink',
          prompts: [
            { content: 'вода', answer: 'voda' },
            { content: 'чай', answer: 'chai' },
            { content: 'кофе', answer: 'kofe' },
            { content: 'рис', answer: 'ris' },
            { content: 'лапша', answer: 'lapsha' },
            { content: 'хлеб', answer: 'khleb' },
            { content: 'молоко', answer: 'moloko' },
            { content: 'сок', answer: 'sok' },
            { content: 'пиво', answer: 'pivo' },
            { content: 'вино', answer: 'vino' },
            { content: 'яблоко', answer: 'yabloko' },
            { content: 'мясо', answer: 'myaso' },
          ],
        },
        {
          name: 'Common Verbs',
          prompts: [
            { content: 'идти', answer: 'idti' },
            { content: 'делать', answer: 'delat' },
            { content: 'хотеть', answer: 'khotet' },
            { content: 'знать', answer: 'znat' },
            { content: 'понимать', answer: 'ponimat' },
            { content: 'говорить', answer: 'govorit' },
            { content: 'читать', answer: 'chitat' },
            { content: 'писать', answer: 'pisat' },
            { content: 'есть', answer: 'yest' },
            { content: 'пить', answer: 'pit' },
            { content: 'работать', answer: 'rabotat' },
            { content: 'жить', answer: 'zhit' },
          ],
        },
        {
          name: 'Family',
          prompts: [
            { content: 'мама', answer: 'mama' },
            { content: 'папа', answer: 'papa' },
            { content: 'брат', answer: 'brat' },
            { content: 'сестра', answer: 'sestra' },
            { content: 'сын', answer: 'syn' },
            { content: 'дочь', answer: 'doch' },
            { content: 'семья', answer: 'semya' },
            { content: 'друг', answer: 'drug' },
            { content: 'подруга', answer: 'podruga' },
            { content: 'муж', answer: 'muzh' },
            { content: 'жена', answer: 'zhena' },
            { content: 'родители', answer: 'roditeli' },
          ],
        },
        {
          name: 'Days & Time',
          prompts: [
            { content: 'понедельник', answer: 'ponedelnik' },
            { content: 'вторник', answer: 'vtornik' },
            { content: 'среда', answer: 'sreda' },
            { content: 'четверг', answer: 'chetverg' },
            { content: 'пятница', answer: 'pyatnitsa' },
            { content: 'суббота', answer: 'subbota' },
            { content: 'воскресенье', answer: 'voskresene' },
            { content: 'сегодня', answer: 'segodnya' },
            { content: 'завтра', answer: 'zavtra' },
            { content: 'вчера', answer: 'vchera' },
          ],
        },
        {
          name: 'Places',
          prompts: [
            { content: 'школа', answer: 'shkola' },
            { content: 'дом', answer: 'dom' },
            { content: 'магазин', answer: 'magazin' },
            { content: 'больница', answer: 'bolnitsa' },
            { content: 'станция', answer: 'stantsiya' },
            { content: 'парк', answer: 'park' },
            { content: 'компания', answer: 'kompaniya' },
            { content: 'банк', answer: 'bank' },
            { content: 'библиотека', answer: 'biblioteka' },
            { content: 'аэропорт', answer: 'aeroport' },
            { content: 'рынок', answer: 'rynok' },
            { content: 'ресторан', answer: 'restoran' },
          ],
        },
      ],
    },
  ];

  // Idempotent upsert by names (no unique constraints required)
  for (const l of langs) {
    let lang = await prisma.lang.findFirst({ where: { name: l.name } });
    if (!lang) {
      lang = await prisma.lang.create({ data: { name: l.name } });
    }
    for (const u of l.units) {
      let unit = await prisma.unit.findFirst({ where: { name: u.name, langId: lang.id } });
      if (!unit) {
        unit = await prisma.unit.create({ data: { name: u.name, langId: lang.id } });
      }
      for (const p of u.prompts) {
        const existing = await prisma.prompt.findFirst({ where: { unitId: unit.id, content: p.content } });
        if (!existing) {
          await prisma.prompt.create({ data: { content: p.content, answer: p.answer, unitId: unit.id } });
        } else if (existing.answer !== p.answer) {
          await prisma.prompt.update({ where: { id: existing.id }, data: { answer: p.answer } });
        }
      }
    }
  }

  const langCount = await prisma.lang.count();
  const unitCount = await prisma.unit.count();
  const promptCount = await prisma.prompt.count();
  console.log(`Seeded: ${langCount} langs, ${unitCount} units, ${promptCount} prompts.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
